#!/bin/bash

# TODO: Include all the stuff
# TODO: Make idempotent

# Checkout submodules
yadm submodule update --init --recursive

mkdir ~/Projects

# Install yadm?

# Set gnome settings
gsettings set org.freedesktop.ibus.panel.emoji hotkey '[]'

# Install cli tools
sudo dnf install -y neovim zsh fzf exa bat fd-find ripgrep startship ShellCheck wl-clipboard

# Install development tools
sudo dnf in @"Development Tools" @"C Development Tools and Libraries" -y
sudo dnf install -y nodejs cmake ninja-build clang clang-tools-extra golang cargo rust rustfmt clippy

# Install nerd-fonts

# Install github cli
sudo dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
sudo dnf install -y gh

# Setup git credential manager
# Fedora change: https://discussion.fedoraproject.org/t/attention-git-credential-libsecret-for-storing-git-passwords-in-the-gnome-keyring-is-now-an-extra-package/18275?u=rugk

# Install python tools
sudo dnf install -y poetry black python3-isort

# Install node tools
npm install --global \
	tree-sitter-cli \
	prettier @fsouza/prettierd \
	eslint eslint_d

# Install language servers

## NPM based ones

npm install --global \
	typescript typescript-language-server \
	vscode-langservers-extracted \
	yaml-language-server \
	pyright

## Lua language server

### Install dependencies
sudo dnf install -y libstdc++-static

### Clone and initialize submodules
git clone https://github.com/sumneko/lua-language-server ~/Projects/lua-language-server
cd ~/Projects/lua-language-server
git submodule update --init --recursive

### Build build system
cd ./3rd/luamake
./compile/install.sh

### Build binary
cd ../..
./3rd/luamake/luamake rebuild

cd ~
