#!/bin/bash

# TODO: Include all the stuff
# TODO: Make idempotent

# Checkout submodules
yadm submodule update --init --recursive

# Make directories
mkdir ~/Projects
mkdir ~/.local/bin

# Set gnome settings
gsettings set org.freedesktop.ibus.panel.emoji hotkey '[]'

# Install cli tools
sudo dnf install -y neovim zsh direnv fzf exa bat git-delta fd-find ripgrep startship ShellCheck wl-clipboard xsel xclip

# Install development tools
sudo dnf in @"Development Tools" @"C Development Tools and Libraries" -y
sudo dnf install -y nodejs cmake ninja-build clang clang-tools-extra golang cargo rust rustfmt clippy

# Install rust-analyzer by downloading latest github release
# NOTE: This also updates rust-analyzer
curl -L https://github.com/rust-analyzer/rust-analyzer/releases/latest/download/rust-analyzer-x86_64-unknown-linux-gnu.gz \
	| gunzip -c - > ~/.local/bin/rust-analyzer
chmod +x ~/.local/bin/rust-analyzer

# Install nerd-fonts
if [ ! -d "$HOME/Projects/nerd-fonts/" ]; then
	echo "Installing nerd-fonts"
	git clone https://github.com/ryanoasis/nerd-fonts ~/Projects/nerd-fonts --depth 1
	cd ~/Projects/nerd-fonts/ || exit
	./install.sh
	cd ~ || exit
fi

# Install github cli
sudo dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
sudo dnf install -y gh

# Setup git credential manager
# Fedora change: https://discussion.fedoraproject.org/t/attention-git-credential-libsecret-for-storing-git-passwords-in-the-gnome-keyring-is-now-an-extra-package/18275?u=rugk

# Install python tools
sudo dnf install -y poetry black python3-isort

# Install node tools
npm install --global \
	tree-sitter-cli \
	prettier @fsouza/prettierd \
	eslint eslint_d

# Install language servers

## NPM based ones

npm install --global \
	typescript typescript-language-server \
	vscode-langservers-extracted \
	yaml-language-server \
	pyright

## Lua language server

### Install dependencies
sudo dnf install -y libstdc++-static

### Clone and initialize submodules
git clone https://github.com/sumneko/lua-language-server ~/Projects/lua-language-server
cd ~/Projects/lua-language-server
git submodule update --init --recursive

### Build build system
cd ./3rd/luamake
./compile/install.sh

### Build binary
cd ../..
./3rd/luamake/luamake rebuild

cd ~
