add_newline = false

format = """
$directory\
$git_branch\
$git_state\
$git_status\
$docker_context\
$rust\
$python\
$golang\
$nodejs\
$jobs\
$cmd_duration\
$line_break\
$character\
"""

scan_timeout = 50 # ms
command_timeout = 150 # ms

[fill]
symbol = "─"
style = "bold green"

[character]
success_symbol = "[➜ ](bold green)"

