"$schema" = "https://starship.rs/config-schema.json"

add_newline = false

# Almost default
# format = """
# $directory\
# $git_branch\
# $git_state\
# $git_status\
# $docker_context\
# $rust\
# $python\
# $golang\
# $nodejs\
# $jobs\
# $cmd_duration\
# $line_break\
# $character\
# """

# Brackets
# format = """
# [┌](bold green)$fill
# [│](bold green)$directory$git_branch$git_state$git_status$rust$python$golang$nodejs$jobs
# [└](bold green)$character"""

# Left and right
format = """
$character\
"""
right_format = """
$directory\
$git_branch\
$git_state\
$git_status\
$docker_context\
$jobs\
$cmd_duration\
"""

scan_timeout = 50 # ms
command_timeout = 150 # ms

[fill]
symbol = "─"
style = "bold green"

[character]
success_symbol = "[➜ ](bold green)"
error_symbol = "[➜ ](bold red)"

